spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true             # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7003/eureka   #单机版 只有几个eureka
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7004.com:7004/eureka #,http://eureka7005.com:7005/eureka  #
  instance:
      instance-id: provider-dept #修改实例名称
      prefer-ip-address: true #是否显示ip地址

#此处就是 微服务 的info 其中${} 就是读取的父工程中的信息
info:
  app.name:  atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true             # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7003/eureka   #单机版 只有几个eureka
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7004.com:7004/eureka #,http://eureka7005.com:7005/eureka  #
  instance:
      instance-id: provider-dept #修改实例名称
      prefer-ip-address: true #是否显示ip地址

#此处就是 微服务 的info 其中${} 就是读取的父工程中的信息
info:
  app.name:  atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


